### ISSUE TITLE
InDesign 2.5 Content & Design Checklist

### ISSUE THREAD

**Issue by caseyg** [freecooperunion/disorientation#55]
## Content Replacements / Updates (Casey)
- [x] Intro 
- [x] disContents
- [x] Lowdown
  - [x] Direct Action & Free Cooper Union
  - [x] Ivory Tower
  - [x] Working Group
  - [x] Legal Action & The Committee to Save Cooper Union
  - [x] Code of Conduct & Campus Militarization
  - [x] FJC, BDA, and SOS: Changings of the Guards
  - [x] “Half-Tuition” & #NewTuition
  - [x] Attorney General Investigates
- [x]  Background
- [x] Toolkit (can we rename this??)
- [ ] Vision Platter
- [x] Colophon
- Toolkit
  - [x] Remove the word “dynamic” from “dynamic timeline”
## Design (Troy)
- Cover
  - [x] Update design in InDesign
  - [x] Check with Peng on margins
- Structure
  - [ ] Change section order to: 
    1. Jam is Fired
    2. Vision Platter
    3. Lowdown
    4. Background
    5. Toolkit
- Intro 
  - [x] Ping pong balls with money signs bleeding off bottom of page?
  - [x] Unflipped umbrella girl (umbrella down) on front inside cover
- disContents
  - [x] Bold names of contributors in descriptions of Background articles.
  - [x] Double-check all page numbers or COMPLETELY randomize.
- Lowdown
  - [x] check page numbers (they are wrong)
- Direct Action & Free Cooper Union
  - [x] there should a page break starting with "[Omnivalent narrator cues dream sequence flashback]" until "Direct Action Gets the Goods" and this content should feel like a dream sequence aka squiggle the text like a flashback
- Ivory Tower
  - [x] Replace Sundance pic with Pioneer Works Pic
- Working Group
  - [x] Make the report wiggly like an image moved on a scanner bed, because it felt like that. Victoria hates whitespace.
- FJC, BDA, and SOS: Changings of the Guards
  - [x] Panic room meme
  - [x] tone down bda imagery
- “Half-Tuition” & #NewTuition
  - [x] added this chapter, need a title text lockup
  - [x] okay whatever charge tuition
  - [x] coke new tuition meme
  - [x] screenshots of dahlberg emails
- Attorney General Investigates
  - [x] added this chapter, need a title text lockup

**Comment by caseyg** [comment]
Casey Stuff:
- [ ] check italics
- [x] jamshed meme imagery
- [x] vision platter intro text
- [ ] new vision platter fries
- [x] jamshed is fired
- [x] sanity check numbering against page numbers on disContents & section landings
- [x] check reading list
- [x] redraw tactic star
- [ ] double check action captions
- [x] run bye bye bo by vic
- [x] unhashtag #newtuition in index
- [x] write Attorney General
- [x] ~~headline collage~~
- [ ] ~~revisit headline collage WOWW if time~~
- [x] take vision platter out of lowdown TOC
- [x] sangu online essays two bullet points
- [x] tool kit TOC: add print resource new spreads, remove word dynamic
- [x] spectrum typo killmenow
- [x] double check the admin
- [ ] phases of a movement explanation
- [x] administrator tic tac toe, 3 firings in the row you get a full scholarship
- [ ] add slack to tools, add google news

**Comment by caseyg** [comment]
inside cover: move in 1/8 inch
page 6, 8: 6 x 9 file
page 10, 11, 12, 13: quarter inch margin left and right
page 14 and 15: bleed size, text flip on .25 margin
page 16: text margin on bottom
page 16 and 17 need bleed size
page 21: bleed size, top text is too close
page 22: bleed size, top and bottom text too close
page 24 25: bleed size
page 26 bleed size
page 27: bleed size
page 32: bleed
page 34, 35: bleed
page 38:
